export const ErrorCode = {
  JWT_EXPIRED: "JWT_EXPIRED",
  JWT_FETCH_FAILED: "JWT_FETCH_FAILED",
  MODAL_CONFLICT: "MODAL_CONFLICT",
  MODAL_CLOSE_FAILED: "MODAL_CLOSE_FAILED",
  SDK_NOT_INITIALIZED: "SDK_NOT_INITIALIZED",
  VERSION_INCOMPATIBLE: "VERSION_INCOMPATIBLE",
  NETWORK_ERROR: "NETWORK_ERROR",
  FLOW_NOT_ACTIVE: "FLOW_NOT_ACTIVE",
  INITIALIZATION_FAILED: "INITIALIZATION_FAILED",
  RETRY_EXHAUSTED: "RETRY_EXHAUSTED",
  RATE_LIMITED: "RATE_LIMITED",
  SLIPPAGE_EXCEEDED: "SLIPPAGE_EXCEEDED",
  CIRCUIT_OPEN: "CIRCUIT_OPEN",
  OPERATION_TIMEOUT: "OPERATION_TIMEOUT",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const RETRYABLE_ERRORS: ReadonlySet<ErrorCode> = new Set([
  ErrorCode.JWT_FETCH_FAILED,
  ErrorCode.NETWORK_ERROR,
  ErrorCode.MODAL_CONFLICT,
  ErrorCode.OPERATION_TIMEOUT,
]);
